CREATE ROLE fithubdevelopment WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD '9017fithub7239';

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO fithubdevelopment;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO fithubdevelopment;

GRANT ALL PRIVILEGES ON DATABASE fithub TO fithubdevelopment;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO fithubdevelopment;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO fithubdevelopment;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";